/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScenarioInput = IDL.Record({
  'd7_microSupply' : IDL.Nat,
  'd8_microDemand' : IDL.Nat,
  'd15_tradeStability' : IDL.Nat,
  'd14_positionRisk' : IDL.Nat,
  'd4_microFlow' : IDL.Nat,
  'd9_sectorStrength' : IDL.Nat,
  'd12_assetWeakness' : IDL.Nat,
  'd2_macroFlow' : IDL.Nat,
  'd10_sectorWeakness' : IDL.Nat,
  'd5_macroSupply' : IDL.Nat,
  'd1_macroAccumulation' : IDL.Nat,
  'd6_macroDemand' : IDL.Nat,
  'd13_positionControl' : IDL.Nat,
  'd11_assetStrength' : IDL.Nat,
  'd16_stateStability' : IDL.Nat,
  'd3_microAccumulation' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const Scenario = IDL.Record({
  'created' : IDL.Int,
  'd7_microSupply' : IDL.Nat,
  'd8_microDemand' : IDL.Nat,
  'd15_tradeStability' : IDL.Nat,
  'd14_positionRisk' : IDL.Nat,
  'd4_microFlow' : IDL.Nat,
  'd9_sectorStrength' : IDL.Nat,
  'd12_assetWeakness' : IDL.Nat,
  'd2_macroFlow' : IDL.Nat,
  'd10_sectorWeakness' : IDL.Nat,
  'd5_macroSupply' : IDL.Nat,
  'd1_macroAccumulation' : IDL.Nat,
  'd6_macroDemand' : IDL.Nat,
  'd13_positionControl' : IDL.Nat,
  'updated' : IDL.Int,
  'd11_assetStrength' : IDL.Nat,
  'd16_stateStability' : IDL.Nat,
  'd3_microAccumulation' : IDL.Nat,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'createScenario' : IDL.Func([ScenarioInput], [IDL.Nat], []),
  'deleteScenario' : IDL.Func([IDL.Nat], [], []),
  'getScenario' : IDL.Func([IDL.Nat], [Scenario], ['query']),
  'listAllScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
  'updateScenario' : IDL.Func([IDL.Nat, ScenarioInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScenarioInput = IDL.Record({
    'd7_microSupply' : IDL.Nat,
    'd8_microDemand' : IDL.Nat,
    'd15_tradeStability' : IDL.Nat,
    'd14_positionRisk' : IDL.Nat,
    'd4_microFlow' : IDL.Nat,
    'd9_sectorStrength' : IDL.Nat,
    'd12_assetWeakness' : IDL.Nat,
    'd2_macroFlow' : IDL.Nat,
    'd10_sectorWeakness' : IDL.Nat,
    'd5_macroSupply' : IDL.Nat,
    'd1_macroAccumulation' : IDL.Nat,
    'd6_macroDemand' : IDL.Nat,
    'd13_positionControl' : IDL.Nat,
    'd11_assetStrength' : IDL.Nat,
    'd16_stateStability' : IDL.Nat,
    'd3_microAccumulation' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const Scenario = IDL.Record({
    'created' : IDL.Int,
    'd7_microSupply' : IDL.Nat,
    'd8_microDemand' : IDL.Nat,
    'd15_tradeStability' : IDL.Nat,
    'd14_positionRisk' : IDL.Nat,
    'd4_microFlow' : IDL.Nat,
    'd9_sectorStrength' : IDL.Nat,
    'd12_assetWeakness' : IDL.Nat,
    'd2_macroFlow' : IDL.Nat,
    'd10_sectorWeakness' : IDL.Nat,
    'd5_macroSupply' : IDL.Nat,
    'd1_macroAccumulation' : IDL.Nat,
    'd6_macroDemand' : IDL.Nat,
    'd13_positionControl' : IDL.Nat,
    'updated' : IDL.Int,
    'd11_assetStrength' : IDL.Nat,
    'd16_stateStability' : IDL.Nat,
    'd3_microAccumulation' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'createScenario' : IDL.Func([ScenarioInput], [IDL.Nat], []),
    'deleteScenario' : IDL.Func([IDL.Nat], [], []),
    'getScenario' : IDL.Func([IDL.Nat], [Scenario], ['query']),
    'listAllScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
    'updateScenario' : IDL.Func([IDL.Nat, ScenarioInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };