/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Scenario {
  'created' : bigint,
  'd7_microSupply' : bigint,
  'd8_microDemand' : bigint,
  'd15_tradeStability' : bigint,
  'd14_positionRisk' : bigint,
  'd4_microFlow' : bigint,
  'd9_sectorStrength' : bigint,
  'd12_assetWeakness' : bigint,
  'd2_macroFlow' : bigint,
  'd10_sectorWeakness' : bigint,
  'd5_macroSupply' : bigint,
  'd1_macroAccumulation' : bigint,
  'd6_macroDemand' : bigint,
  'd13_positionControl' : bigint,
  'updated' : bigint,
  'd11_assetStrength' : bigint,
  'd16_stateStability' : bigint,
  'd3_microAccumulation' : bigint,
  'symbol' : string,
}
export interface ScenarioInput {
  'd7_microSupply' : bigint,
  'd8_microDemand' : bigint,
  'd15_tradeStability' : bigint,
  'd14_positionRisk' : bigint,
  'd4_microFlow' : bigint,
  'd9_sectorStrength' : bigint,
  'd12_assetWeakness' : bigint,
  'd2_macroFlow' : bigint,
  'd10_sectorWeakness' : bigint,
  'd5_macroSupply' : bigint,
  'd1_macroAccumulation' : bigint,
  'd6_macroDemand' : bigint,
  'd13_positionControl' : bigint,
  'd11_assetStrength' : bigint,
  'd16_stateStability' : bigint,
  'd3_microAccumulation' : bigint,
  'symbol' : string,
}
export interface _SERVICE {
  'createScenario' : ActorMethod<[ScenarioInput], bigint>,
  'deleteScenario' : ActorMethod<[bigint], undefined>,
  'getScenario' : ActorMethod<[bigint], Scenario>,
  'listAllScenarios' : ActorMethod<[], Array<Scenario>>,
  'updateScenario' : ActorMethod<[bigint, ScenarioInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];