// D16 Hybrid Branch — Seeded Deterministic Mock Data
// Phase H1 + H2: Canonical Asset Mapping + Per-Market State Generation
// IMPORTANT: NO Math.random() anywhere in this file. LCG seeded generator only.
//
// Simulated universe: 32 assets covering a broad cross-section of tradable
// crypto markets. Includes large-cap, mid-cap, L1/L2, DeFi, meme, and emerging
// categories — structurally diverse entry states for realistic operator workflow.

import type {
  CanonicalAssetMarkets,
  CanonicalAssetState,
  MarketDirection,
  MarketExecutionPermission,
  MarketMaturity,
  MarketTrustClass,
  PerMarketState,
} from "./hybridTypes";

// ─── LCG: Linear Congruential Generator ─────────────────────────────────────
// Same seed always produces the same sequence. NO uncontrolled randomness.

function lcg(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
    return s / 0xffffffff;
  };
}

// ─── Phase H1: Canonical Asset Mapping Layer ────────────────────────────────

const ASSET_DEFINITIONS = [
  // ── Tier-1 anchors ──────────────────────────────────────────────────────
  {
    asset: "BTC",
    binanceSpot: "BTCUSDT",
    coinbase: "BTC-USD",
    binanceFutures: "BTCUSDT",
  },
  {
    asset: "ETH",
    binanceSpot: "ETHUSDT",
    coinbase: "ETH-USD",
    binanceFutures: "ETHUSDT",
  },
  {
    asset: "SOL",
    binanceSpot: "SOLUSDT",
    coinbase: "SOL-USD",
    binanceFutures: "SOLUSDT",
  },
  {
    asset: "XRP",
    binanceSpot: "XRPUSDT",
    coinbase: "XRP-USD",
    binanceFutures: "XRPUSDT",
  },
  {
    asset: "DOGE",
    binanceSpot: "DOGEUSDT",
    coinbase: "DOGE-USD",
    binanceFutures: "DOGEUSDT",
  },
  {
    asset: "ADA",
    binanceSpot: "ADAUSDT",
    coinbase: "ADA-USD",
    binanceFutures: "ADAUSDT",
  },
  {
    asset: "LINK",
    binanceSpot: "LINKUSDT",
    coinbase: "LINK-USD",
    binanceFutures: "LINKUSDT",
  },
  {
    asset: "AVAX",
    binanceSpot: "AVAXUSDT",
    coinbase: "AVAX-USD",
    binanceFutures: "AVAXUSDT",
  },
  // ── Extended universe — Layer 1 / large-cap ─────────────────────────────
  {
    asset: "BNB",
    binanceSpot: "BNBUSDT",
    coinbase: "BNB-USD",
    binanceFutures: "BNBUSDT",
  },
  {
    asset: "TRX",
    binanceSpot: "TRXUSDT",
    coinbase: "TRX-USD",
    binanceFutures: "TRXUSDT",
  },
  {
    asset: "TON",
    binanceSpot: "TONUSDT",
    coinbase: "TON-USD",
    binanceFutures: "TONUSDT",
  },
  {
    asset: "DOT",
    binanceSpot: "DOTUSDT",
    coinbase: "DOT-USD",
    binanceFutures: "DOTUSDT",
  },
  {
    asset: "ATOM",
    binanceSpot: "ATOMUSDT",
    coinbase: "ATOM-USD",
    binanceFutures: "ATOMUSDT",
  },
  // ── Extended universe — Layer 2 / ecosystem ──────────────────────────────
  {
    asset: "MATIC",
    binanceSpot: "MATICUSDT",
    coinbase: "MATIC-USD",
    binanceFutures: "MATICUSDT",
  },
  {
    asset: "OP",
    binanceSpot: "OPUSDT",
    coinbase: "OP-USD",
    binanceFutures: "OPUSDT",
  },
  {
    asset: "ARB",
    binanceSpot: "ARBUSDT",
    coinbase: "ARB-USD",
    binanceFutures: "ARBUSDT",
  },
  {
    asset: "SUI",
    binanceSpot: "SUIUSDT",
    coinbase: "SUI-USD",
    binanceFutures: "SUIUSDT",
  },
  {
    asset: "APT",
    binanceSpot: "APTUSDT",
    coinbase: "APT-USD",
    binanceFutures: "APTUSDT",
  },
  // ── Extended universe — DeFi / infrastructure ────────────────────────────
  {
    asset: "UNI",
    binanceSpot: "UNIUSDT",
    coinbase: "UNI-USD",
    binanceFutures: "UNIUSDT",
  },
  {
    asset: "AAVE",
    binanceSpot: "AAVEUSDT",
    coinbase: "AAVE-USD",
    binanceFutures: "AAVEUSDT",
  },
  {
    asset: "LDO",
    binanceSpot: "LDOUSDT",
    coinbase: "LDO-USD",
    binanceFutures: "LDOUSDT",
  },
  {
    asset: "INJ",
    binanceSpot: "INJUSDT",
    coinbase: "INJ-USD",
    binanceFutures: "INJUSDT",
  },
  // ── Extended universe — AI / narrative ───────────────────────────────────
  {
    asset: "FET",
    binanceSpot: "FETUSDT",
    coinbase: "FET-USD",
    binanceFutures: "FETUSDT",
  },
  {
    asset: "RNDR",
    binanceSpot: "RNDRUSDT",
    coinbase: "RNDR-USD",
    binanceFutures: "RNDRUSDT",
  },
  {
    asset: "TAO",
    binanceSpot: "TAOUSDT",
    coinbase: "TAO-USD",
    binanceFutures: "TAOUSDT",
  },
  // ── Extended universe — meme / high-vol ─────────────────────────────────
  {
    asset: "SHIB",
    binanceSpot: "SHIBUSDT",
    coinbase: "SHIB-USD",
    binanceFutures: "SHIBUSDT",
  },
  {
    asset: "PEPE",
    binanceSpot: "PEPEUSDT",
    coinbase: "PEPE-USD",
    binanceFutures: "PEPEUSDT",
  },
  {
    asset: "WIF",
    binanceSpot: "WIFUSDT",
    coinbase: "WIF-USD",
    binanceFutures: "WIFUSDT",
  },
  {
    asset: "BONK",
    binanceSpot: "BONKUSDT",
    coinbase: "BONK-USD",
    binanceFutures: "BONKUSDT",
  },
  // ── Extended universe — exchange / utility ───────────────────────────────
  {
    asset: "FTT",
    binanceSpot: "FTTUSDT",
    coinbase: "FTT-USD",
    binanceFutures: "FTTUSDT",
  },
  {
    asset: "CRV",
    binanceSpot: "CRVUSDT",
    coinbase: "CRV-USD",
    binanceFutures: "CRVUSDT",
  },
  {
    asset: "TIA",
    binanceSpot: "TIAUSDT",
    coinbase: "TIA-USD",
    binanceFutures: "TIAUSDT",
  },
] as const;

export const CANONICAL_ASSET_MAPPINGS: CanonicalAssetMarkets[] =
  ASSET_DEFINITIONS.map((def) => ({
    asset: def.asset,
    binanceSpotSymbol: def.binanceSpot,
    coinbaseSpotProduct: def.coinbase,
    binanceFuturesSymbol: def.binanceFutures,
    availability: {
      binanceSpot: true,
      coinbaseSpot: true,
      binanceFutures: true,
    },
  }));

// ─── Phase H2: Per-Market State Generation ──────────────────────────────────

// Asset profile definitions — these are the architecturally meaningful distinctions.
// Numeric scores are generated within the profile's valid range using the seeded LCG.

type AssetProfile = {
  seed: number;
  asset: string;
  binanceSpot: MarketStateProfile;
  coinbaseSpot: MarketStateProfile;
  binanceFutures: MarketStateProfile;
};

type MarketStateProfile = {
  direction: MarketDirection;
  maturity: MarketMaturity;
  trustClass: MarketTrustClass;
  executionPermission: MarketExecutionPermission;
  structuralRange: [number, number];
  activationRange: [number, number];
  entryReadinessRange: [number, number];
  runtimeTrustRange: [number, number];
  mainBlockerTemplate: string | null;
};

const ASSET_PROFILES: AssetProfile[] = [
  {
    // BTC (seed 1001): Futures leads spot — futures ACTIVE, spot FORMING
    seed: 1001,
    asset: "BTC",
    binanceFutures: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [68, 78],
      activationRange: [70, 82],
      entryReadinessRange: [55, 68],
      runtimeTrustRange: [82, 92],
      mainBlockerTemplate: "Spot confirmation insufficient for exact entry",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [45, 58],
      activationRange: [38, 52],
      entryReadinessRange: [28, 42],
      runtimeTrustRange: [62, 74],
      mainBlockerTemplate: "Structure forming, awaiting futures confirmation",
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "BREWING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [35, 48],
      activationRange: [28, 42],
      entryReadinessRange: [18, 32],
      runtimeTrustRange: [60, 72],
      mainBlockerTemplate: "Early stage development, no execution plan",
    },
  },
  {
    // ETH (seed 1002): Full three-market alignment — all LONG/READY/HIGH_TRUST/EXACT_PLAN
    seed: 1002,
    asset: "ETH",
    binanceFutures: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [82, 92],
      activationRange: [85, 93],
      entryReadinessRange: [80, 90],
      runtimeTrustRange: [88, 95],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [80, 90],
      activationRange: [82, 91],
      entryReadinessRange: [78, 88],
      runtimeTrustRange: [85, 93],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [79, 89],
      activationRange: [81, 90],
      entryReadinessRange: [76, 86],
      runtimeTrustRange: [84, 92],
      mainBlockerTemplate: null,
    },
  },
  {
    // SOL (seed 1003): Direction conflict — futures SHORT, spot LONG, coinbase NEUTRAL
    seed: 1003,
    asset: "SOL",
    binanceFutures: {
      direction: "SHORT",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [55, 68],
      activationRange: [58, 70],
      entryReadinessRange: [40, 55],
      runtimeTrustRange: [62, 75],
      mainBlockerTemplate:
        "Direction conflict with spot markets — entry blocked",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [42, 55],
      activationRange: [35, 48],
      entryReadinessRange: [25, 38],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Opposite direction to futures — no plan available",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [28, 40],
      activationRange: [22, 35],
      entryReadinessRange: [12, 25],
      runtimeTrustRange: [38, 52],
      mainBlockerTemplate: "Neutral, reduced trust — insufficient conviction",
    },
  },
  {
    // XRP (seed 1004): Spot leads futures — spot ACTIVE, futures FORMING
    seed: 1004,
    asset: "XRP",
    binanceFutures: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [44, 56],
      activationRange: [38, 52],
      entryReadinessRange: [28, 42],
      runtimeTrustRange: [60, 72],
      mainBlockerTemplate: "Lagging behind spot — awaiting futures activation",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [62, 74],
      activationRange: [65, 76],
      entryReadinessRange: [55, 68],
      runtimeTrustRange: [68, 80],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [68, 80],
      activationRange: [70, 82],
      entryReadinessRange: [62, 75],
      runtimeTrustRange: [75, 86],
      mainBlockerTemplate: null,
    },
  },
  {
    // DOGE (seed 1005): Futures overextended — futures READY, spots EARLY with reduced trust
    seed: 1005,
    asset: "DOGE",
    binanceFutures: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [62, 74],
      activationRange: [65, 76],
      entryReadinessRange: [58, 70],
      runtimeTrustRange: [65, 76],
      mainBlockerTemplate:
        "Spot markets not yet confirming — futures overextended",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "EARLY",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [18, 30],
      activationRange: [12, 25],
      entryReadinessRange: [8, 20],
      runtimeTrustRange: [32, 44],
      mainBlockerTemplate: "Very early stage, reduced trust — no plan",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [15, 28],
      activationRange: [10, 22],
      entryReadinessRange: [5, 18],
      runtimeTrustRange: [28, 40],
      mainBlockerTemplate:
        "Neutral direction, very early — insufficient structure",
    },
  },
  {
    // ADA (seed 1006): Trust conflict — futures valid, spot INVALID_RUNTIME, coinbase LOW_TRUST
    seed: 1006,
    asset: "ADA",
    binanceFutures: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [65, 76],
      activationRange: [68, 80],
      entryReadinessRange: [52, 65],
      runtimeTrustRange: [82, 92],
      mainBlockerTemplate: "Spot trust conflict prevents exact entry",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "INVALID_RUNTIME",
      executionPermission: "NO_PLAN",
      structuralRange: [30, 44],
      activationRange: [22, 36],
      entryReadinessRange: [12, 26],
      runtimeTrustRange: [8, 18],
      mainBlockerTemplate: "INVALID_RUNTIME: spot data feed unreliable",
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "BREWING",
      trustClass: "LOW_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [20, 34],
      activationRange: [15, 28],
      entryReadinessRange: [8, 20],
      runtimeTrustRange: [18, 30],
      mainBlockerTemplate: "Low trust — not reliable enough for execution",
    },
  },
  {
    // LINK (seed 1007): Coinbase leads Binance spot — coinbase ACTIVE, binanceSpot BREWING, futures FORMING
    seed: 1007,
    asset: "LINK",
    binanceFutures: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [42, 55],
      activationRange: [36, 50],
      entryReadinessRange: [26, 40],
      runtimeTrustRange: [60, 72],
      mainBlockerTemplate: "Futures lagging — spot markets leading",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "BREWING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [32, 45],
      activationRange: [26, 40],
      entryReadinessRange: [16, 30],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Still brewing — Coinbase leading move",
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [60, 72],
      activationRange: [62, 74],
      entryReadinessRange: [52, 65],
      runtimeTrustRange: [66, 78],
      mainBlockerTemplate: null,
    },
  },
  {
    // AVAX (seed 1008): Watch-only, maturity conflict — futures ARMED, binanceSpot EARLY, coinbase SHORT
    seed: 1008,
    asset: "AVAX",
    binanceFutures: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [58, 70],
      activationRange: [60, 72],
      entryReadinessRange: [48, 62],
      runtimeTrustRange: [62, 74],
      mainBlockerTemplate: "Maturity conflict — spot not aligned",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "EARLY",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [15, 28],
      activationRange: [10, 22],
      entryReadinessRange: [5, 18],
      runtimeTrustRange: [30, 42],
      mainBlockerTemplate: "Early stage, reduced trust — no structure yet",
    },
    coinbaseSpot: {
      direction: "SHORT",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [25, 38],
      activationRange: [20, 32],
      entryReadinessRange: [10, 22],
      runtimeTrustRange: [35, 48],
      mainBlockerTemplate: "Direction conflict — SHORT while futures LONG",
    },
  },

  // ── Extended universe profiles ────────────────────────────────────────────

  {
    // BNB (seed 2001): Strong continuation — all markets ARMED/ACTIVE, good trust
    seed: 2001,
    asset: "BNB",
    binanceFutures: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [74, 84],
      activationRange: [76, 86],
      entryReadinessRange: [68, 80],
      runtimeTrustRange: [80, 90],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [70, 80],
      activationRange: [72, 82],
      entryReadinessRange: [64, 76],
      runtimeTrustRange: [78, 88],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [65, 76],
      activationRange: [68, 78],
      entryReadinessRange: [58, 70],
      runtimeTrustRange: [72, 82],
      mainBlockerTemplate: null,
    },
  },
  {
    // TRX (seed 2002): Flat/neutral — no clear direction, watch-only
    seed: 2002,
    asset: "TRX",
    binanceFutures: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [28, 42],
      activationRange: [22, 36],
      entryReadinessRange: [12, 26],
      runtimeTrustRange: [55, 68],
      mainBlockerTemplate: "No directional conviction — watch only",
    },
    binanceSpot: {
      direction: "NEUTRAL",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [30, 44],
      activationRange: [24, 38],
      entryReadinessRange: [14, 28],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Directionally unclear — no plan",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [22, 35],
      activationRange: [18, 30],
      entryReadinessRange: [8, 20],
      runtimeTrustRange: [40, 54],
      mainBlockerTemplate: "Neutral + reduced trust — insufficient",
    },
  },
  {
    // TON (seed 2003): Breakout candidate — all LONG, ARMED/ACTIVE, building momentum
    seed: 2003,
    asset: "TON",
    binanceFutures: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [62, 74],
      activationRange: [64, 76],
      entryReadinessRange: [52, 66],
      runtimeTrustRange: [76, 86],
      mainBlockerTemplate: "Awaiting spot confirmation for full permission",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [60, 72],
      activationRange: [62, 74],
      entryReadinessRange: [50, 64],
      runtimeTrustRange: [68, 80],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [40, 54],
      activationRange: [34, 48],
      entryReadinessRange: [24, 38],
      runtimeTrustRange: [62, 74],
      mainBlockerTemplate: "Coinbase lagging — formation incomplete",
    },
  },
  {
    // DOT (seed 2004): Short setup — all SHORT, ACTIVE/READY, strong short conviction
    seed: 2004,
    asset: "DOT",
    binanceFutures: {
      direction: "SHORT",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [72, 82],
      activationRange: [74, 84],
      entryReadinessRange: [65, 78],
      runtimeTrustRange: [78, 88],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "SHORT",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [65, 76],
      activationRange: [68, 78],
      entryReadinessRange: [58, 70],
      runtimeTrustRange: [70, 82],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "SHORT",
      maturity: "ARMED",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [60, 72],
      activationRange: [62, 74],
      entryReadinessRange: [50, 64],
      runtimeTrustRange: [65, 76],
      mainBlockerTemplate: "Coinbase not yet at execution maturity",
    },
  },
  {
    // ATOM (seed 2005): Exact entry aligned — strongest SHORT setup in the pool
    seed: 2005,
    asset: "ATOM",
    binanceFutures: {
      direction: "SHORT",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [80, 90],
      activationRange: [82, 92],
      entryReadinessRange: [78, 88],
      runtimeTrustRange: [85, 93],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "SHORT",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [78, 88],
      activationRange: [80, 90],
      entryReadinessRange: [76, 86],
      runtimeTrustRange: [83, 91],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "SHORT",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [76, 86],
      activationRange: [78, 88],
      entryReadinessRange: [74, 84],
      runtimeTrustRange: [81, 90],
      mainBlockerTemplate: null,
    },
  },
  {
    // MATIC (seed 2006): Degrading setup — was ACTIVE, now breaking down
    seed: 2006,
    asset: "MATIC",
    binanceFutures: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [52, 65],
      activationRange: [54, 66],
      entryReadinessRange: [40, 54],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Spot confirmation dropping — momentum weakening",
    },
    binanceSpot: {
      direction: "NEUTRAL",
      maturity: "FORMING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [25, 40],
      activationRange: [20, 34],
      entryReadinessRange: [10, 24],
      runtimeTrustRange: [35, 50],
      mainBlockerTemplate: "Direction lost — structure degrading",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [20, 34],
      activationRange: [15, 28],
      entryReadinessRange: [5, 18],
      runtimeTrustRange: [32, 46],
      mainBlockerTemplate: "Neutral with reduced trust — no execution path",
    },
  },
  {
    // OP (seed 2007): L2 breakout — futures LONG/ARMED, building toward EXACT
    seed: 2007,
    asset: "OP",
    binanceFutures: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [65, 76],
      activationRange: [67, 78],
      entryReadinessRange: [55, 68],
      runtimeTrustRange: [78, 88],
      mainBlockerTemplate: "Spot confirmation lag — 2-of-3 not yet met",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [62, 74],
      activationRange: [64, 76],
      entryReadinessRange: [52, 65],
      runtimeTrustRange: [68, 80],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [60, 72],
      activationRange: [62, 74],
      entryReadinessRange: [50, 63],
      runtimeTrustRange: [66, 78],
      mainBlockerTemplate: null,
    },
  },
  {
    // ARB (seed 2008): Momentum fading — was high-quality, now showing divergence
    seed: 2008,
    asset: "ARB",
    binanceFutures: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [38, 52],
      activationRange: [32, 46],
      entryReadinessRange: [22, 36],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Futures direction reversed — now forming new base",
    },
    binanceSpot: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [22, 36],
      activationRange: [16, 30],
      entryReadinessRange: [8, 20],
      runtimeTrustRange: [35, 48],
      mainBlockerTemplate: "No directional structure — brewing only",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "LOW_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [10, 22],
      activationRange: [8, 18],
      entryReadinessRange: [2, 12],
      runtimeTrustRange: [18, 30],
      mainBlockerTemplate: "Low trust, early stage — not viable",
    },
  },
  {
    // SUI (seed 2009): Exact LONG — full-stack aligned, highest quality emerging asset
    seed: 2009,
    asset: "SUI",
    binanceFutures: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [83, 93],
      activationRange: [85, 94],
      entryReadinessRange: [80, 90],
      runtimeTrustRange: [87, 95],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [80, 90],
      activationRange: [82, 91],
      entryReadinessRange: [77, 87],
      runtimeTrustRange: [84, 93],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [74, 84],
      activationRange: [76, 86],
      entryReadinessRange: [68, 80],
      runtimeTrustRange: [80, 90],
      mainBlockerTemplate: null,
    },
  },
  {
    // APT (seed 2010): Provisional SHORT — futures/spot aligned SHORT, coinbase neutral
    seed: 2010,
    asset: "APT",
    binanceFutures: {
      direction: "SHORT",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [60, 72],
      activationRange: [62, 74],
      entryReadinessRange: [52, 65],
      runtimeTrustRange: [65, 77],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "SHORT",
      maturity: "ARMED",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [62, 74],
      activationRange: [64, 76],
      entryReadinessRange: [54, 67],
      runtimeTrustRange: [67, 79],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "FORMING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [28, 42],
      activationRange: [22, 36],
      entryReadinessRange: [12, 26],
      runtimeTrustRange: [38, 52],
      mainBlockerTemplate: "Coinbase neutral — 2-of-3 SHORT not confirmed",
    },
  },
  {
    // UNI (seed 2011): DeFi recovery — building from low, BREWING/FORMING across markets
    seed: 2011,
    asset: "UNI",
    binanceFutures: {
      direction: "LONG",
      maturity: "BREWING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [35, 50],
      activationRange: [28, 44],
      entryReadinessRange: [18, 32],
      runtimeTrustRange: [55, 68],
      mainBlockerTemplate: "Structure forming — not actionable yet",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [38, 52],
      activationRange: [30, 46],
      entryReadinessRange: [20, 34],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Early directional structure, no execution plan",
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "BREWING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [30, 45],
      activationRange: [24, 38],
      entryReadinessRange: [14, 28],
      runtimeTrustRange: [54, 66],
      mainBlockerTemplate: "Early stage — all markets still brewing",
    },
  },
  {
    // AAVE (seed 2012): DeFi high conviction SHORT — decoupled from market beta
    seed: 2012,
    asset: "AAVE",
    binanceFutures: {
      direction: "SHORT",
      maturity: "ACTIVE",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [65, 76],
      activationRange: [67, 78],
      entryReadinessRange: [57, 70],
      runtimeTrustRange: [78, 88],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "SHORT",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [68, 78],
      activationRange: [70, 80],
      entryReadinessRange: [62, 74],
      runtimeTrustRange: [80, 90],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "SHORT",
      maturity: "ARMED",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [62, 74],
      activationRange: [64, 76],
      entryReadinessRange: [54, 68],
      runtimeTrustRange: [70, 82],
      mainBlockerTemplate: null,
    },
  },
  {
    // LDO (seed 2013): Liquid staking thesis — LONG breakout building
    seed: 2013,
    asset: "LDO",
    binanceFutures: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [55, 68],
      activationRange: [57, 70],
      entryReadinessRange: [44, 58],
      runtimeTrustRange: [62, 74],
      mainBlockerTemplate: "Spot markets lagging behind futures lead",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [40, 54],
      activationRange: [34, 48],
      entryReadinessRange: [24, 38],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Lagging behind futures — structure forming",
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [28, 42],
      activationRange: [22, 36],
      entryReadinessRange: [12, 26],
      runtimeTrustRange: [40, 55],
      mainBlockerTemplate: "Brewing with reduced trust — not ready",
    },
  },
  {
    // INJ (seed 2014): Near-exact LONG — all markets aligned, strong across the board
    seed: 2014,
    asset: "INJ",
    binanceFutures: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [82, 92],
      activationRange: [84, 93],
      entryReadinessRange: [79, 89],
      runtimeTrustRange: [86, 94],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [76, 86],
      activationRange: [78, 88],
      entryReadinessRange: [72, 82],
      runtimeTrustRange: [82, 91],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [70, 80],
      activationRange: [72, 82],
      entryReadinessRange: [62, 74],
      runtimeTrustRange: [78, 88],
      mainBlockerTemplate: null,
    },
  },
  {
    // FET (seed 2015): AI narrative — forming breakout, mixed trust
    seed: 2015,
    asset: "FET",
    binanceFutures: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [58, 70],
      activationRange: [60, 72],
      entryReadinessRange: [48, 62],
      runtimeTrustRange: [64, 76],
      mainBlockerTemplate: "Spot lag — breakout not fully confirmed",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [58, 70],
      activationRange: [60, 72],
      entryReadinessRange: [50, 63],
      runtimeTrustRange: [62, 74],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [40, 54],
      activationRange: [34, 48],
      entryReadinessRange: [24, 38],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Coinbase trailing — structure still forming",
    },
  },
  {
    // RNDR (seed 2016): AI/rendering — runtime pressure, trust degrading
    seed: 2016,
    asset: "RNDR",
    binanceFutures: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [30, 44],
      activationRange: [24, 38],
      entryReadinessRange: [14, 28],
      runtimeTrustRange: [38, 52],
      mainBlockerTemplate: "Runtime trust degraded — feed reliability concern",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "BREWING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [35, 50],
      activationRange: [28, 44],
      entryReadinessRange: [18, 32],
      runtimeTrustRange: [55, 68],
      mainBlockerTemplate: "Still brewing — not actionable",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "LOW_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [12, 24],
      activationRange: [8, 18],
      entryReadinessRange: [2, 12],
      runtimeTrustRange: [16, 28],
      mainBlockerTemplate: "Low trust + early stage — not viable",
    },
  },
  {
    // TAO (seed 2017): AI high-momentum — all LONG/READY, near-exact alignment
    seed: 2017,
    asset: "TAO",
    binanceFutures: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [76, 86],
      activationRange: [78, 88],
      entryReadinessRange: [70, 82],
      runtimeTrustRange: [82, 91],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [72, 82],
      activationRange: [74, 84],
      entryReadinessRange: [65, 78],
      runtimeTrustRange: [78, 88],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [66, 78],
      activationRange: [68, 80],
      entryReadinessRange: [58, 72],
      runtimeTrustRange: [70, 82],
      mainBlockerTemplate: null,
    },
  },
  {
    // SHIB (seed 2018): Meme — high vol, erratic, NEUTRAL/EARLY across markets
    seed: 2018,
    asset: "SHIB",
    binanceFutures: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [10, 24],
      activationRange: [6, 18],
      entryReadinessRange: [2, 12],
      runtimeTrustRange: [28, 42],
      mainBlockerTemplate: "Meme volatility — no reliable structural signal",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "EARLY",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [12, 26],
      activationRange: [8, 20],
      entryReadinessRange: [3, 14],
      runtimeTrustRange: [30, 44],
      mainBlockerTemplate: "Very early, low structure — meme behavior",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "LOW_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [8, 18],
      activationRange: [4, 14],
      entryReadinessRange: [1, 8],
      runtimeTrustRange: [18, 30],
      mainBlockerTemplate: "Low trust + early stage — excluded from execution",
    },
  },
  {
    // PEPE (seed 2019): Meme LONG spike — brief activation window, high trust briefly
    seed: 2019,
    asset: "PEPE",
    binanceFutures: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [52, 66],
      activationRange: [55, 68],
      entryReadinessRange: [40, 54],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Spot confirmation lagging for meme asset",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [38, 52],
      activationRange: [32, 46],
      entryReadinessRange: [22, 36],
      runtimeTrustRange: [55, 68],
      mainBlockerTemplate: "Meme spike — structure still forming",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [18, 32],
      activationRange: [12, 26],
      entryReadinessRange: [5, 16],
      runtimeTrustRange: [32, 46],
      mainBlockerTemplate: "Coinbase not participating in meme move",
    },
  },
  {
    // WIF (seed 2020): Solana meme — LONG, decent structure, limited eligibility
    seed: 2020,
    asset: "WIF",
    binanceFutures: {
      direction: "LONG",
      maturity: "ARMED",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [55, 68],
      activationRange: [57, 70],
      entryReadinessRange: [44, 58],
      runtimeTrustRange: [60, 73],
      mainBlockerTemplate: "Limited market coverage reduces conviction",
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [58, 70],
      activationRange: [60, 72],
      entryReadinessRange: [50, 63],
      runtimeTrustRange: [62, 74],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [22, 36],
      activationRange: [16, 30],
      entryReadinessRange: [8, 20],
      runtimeTrustRange: [35, 50],
      mainBlockerTemplate: "Coinbase not tracking this asset",
    },
  },
  {
    // BONK (seed 2021): Solana meme, blocked — low trust across all markets
    seed: 2021,
    asset: "BONK",
    binanceFutures: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "LOW_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [12, 24],
      activationRange: [8, 18],
      entryReadinessRange: [2, 12],
      runtimeTrustRange: [20, 34],
      mainBlockerTemplate: "Low trust — meme asset with no execution path",
    },
    binanceSpot: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "LOW_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [8, 20],
      activationRange: [5, 15],
      entryReadinessRange: [1, 8],
      runtimeTrustRange: [16, 28],
      mainBlockerTemplate: "Low trust, no direction — excluded",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "INVALID_RUNTIME",
      executionPermission: "NO_PLAN",
      structuralRange: [5, 14],
      activationRange: [2, 10],
      entryReadinessRange: [1, 5],
      runtimeTrustRange: [4, 12],
      mainBlockerTemplate: "INVALID_RUNTIME: coinbase not tracking this meme",
    },
  },
  {
    // FTT (seed 2022): Exchange token — degraded, mostly blocked
    seed: 2022,
    asset: "FTT",
    binanceFutures: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [14, 28],
      activationRange: [10, 22],
      entryReadinessRange: [3, 14],
      runtimeTrustRange: [28, 42],
      mainBlockerTemplate: "Structural damage — no reliable direction",
    },
    binanceSpot: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [10, 22],
      activationRange: [6, 16],
      entryReadinessRange: [2, 10],
      runtimeTrustRange: [25, 38],
      mainBlockerTemplate: "Very low structure — not viable",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "EARLY",
      trustClass: "LOW_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [6, 16],
      activationRange: [3, 12],
      entryReadinessRange: [1, 6],
      runtimeTrustRange: [14, 24],
      mainBlockerTemplate: "Low trust — exchange token in recovery",
    },
  },
  {
    // CRV (seed 2023): DeFi SHORT — depeg pressure, short-side building
    seed: 2023,
    asset: "CRV",
    binanceFutures: {
      direction: "SHORT",
      maturity: "ARMED",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROJECTED_ONLY",
      structuralRange: [58, 70],
      activationRange: [60, 72],
      entryReadinessRange: [48, 62],
      runtimeTrustRange: [64, 76],
      mainBlockerTemplate: "Spot not yet confirming short conviction",
    },
    binanceSpot: {
      direction: "SHORT",
      maturity: "FORMING",
      trustClass: "GOOD_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [40, 54],
      activationRange: [34, 48],
      entryReadinessRange: [24, 38],
      runtimeTrustRange: [58, 70],
      mainBlockerTemplate: "Forming short — not yet actionable",
    },
    coinbaseSpot: {
      direction: "NEUTRAL",
      maturity: "BREWING",
      trustClass: "REDUCED_TRUST",
      executionPermission: "NO_PLAN",
      structuralRange: [22, 36],
      activationRange: [16, 30],
      entryReadinessRange: [6, 18],
      runtimeTrustRange: [35, 48],
      mainBlockerTemplate: "Coinbase neutral — cross-market not aligned",
    },
  },
  {
    // TIA (seed 2024): Data availability narrative — strong LONG near-exact
    seed: 2024,
    asset: "TIA",
    binanceFutures: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "EXACT_PLAN",
      structuralRange: [80, 90],
      activationRange: [82, 91],
      entryReadinessRange: [76, 87],
      runtimeTrustRange: [84, 93],
      mainBlockerTemplate: null,
    },
    binanceSpot: {
      direction: "LONG",
      maturity: "READY",
      trustClass: "HIGH_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [74, 84],
      activationRange: [76, 86],
      entryReadinessRange: [68, 80],
      runtimeTrustRange: [80, 90],
      mainBlockerTemplate: null,
    },
    coinbaseSpot: {
      direction: "LONG",
      maturity: "ACTIVE",
      trustClass: "GOOD_TRUST",
      executionPermission: "PROVISIONAL_PLAN",
      structuralRange: [64, 76],
      activationRange: [66, 78],
      entryReadinessRange: [56, 70],
      runtimeTrustRange: [70, 82],
      mainBlockerTemplate: null,
    },
  },
];

// ─── Per-Market State Generator ──────────────────────────────────────────────

function randInRange(rand: () => number, min: number, max: number): number {
  return Math.round(min + rand() * (max - min));
}

function buildPerMarketState(
  profile: MarketStateProfile,
  rand: () => number,
  now: number,
): PerMarketState {
  return {
    direction: profile.direction,
    maturity: profile.maturity,
    trustClass: profile.trustClass,
    executionPermission: profile.executionPermission,
    structuralScore: randInRange(
      rand,
      profile.structuralRange[0],
      profile.structuralRange[1],
    ),
    activationScore: randInRange(
      rand,
      profile.activationRange[0],
      profile.activationRange[1],
    ),
    entryReadiness: randInRange(
      rand,
      profile.entryReadinessRange[0],
      profile.entryReadinessRange[1],
    ),
    runtimeTrust: randInRange(
      rand,
      profile.runtimeTrustRange[0],
      profile.runtimeTrustRange[1],
    ),
    mainBlocker: profile.mainBlockerTemplate,
    updatedAt: now,
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function generateHybridAssetStates(_seed = 42): CanonicalAssetState[] {
  const now = 1712275200000; // Fixed timestamp for determinism: 2024-04-05T00:00:00Z

  return ASSET_PROFILES.map((profile) => {
    // Each asset uses its own seed — different seeds produce different numeric scores
    const rand = lcg(profile.seed);

    return {
      asset: profile.asset,
      binanceFutures: buildPerMarketState(profile.binanceFutures, rand, now),
      binanceSpot: buildPerMarketState(profile.binanceSpot, rand, now),
      coinbaseSpot: buildPerMarketState(profile.coinbaseSpot, rand, now),
    };
  });
}

// Pre-generated with default seed — stable, deterministic, never changes on reload.
export const HYBRID_ASSET_STATES: CanonicalAssetState[] =
  generateHybridAssetStates(42);
