import type { Dimensions } from "./d16Engine";

export type PresetScenario = {
  name: string;
  dims: Dimensions;
};

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    name: "Ideal Candidate",
    dims: {
      d1_macroAccumulation: 85,
      d2_recentAccumulation: 82,
      d3_priceHoldIntegrity: 80,
      d4_compressionQuality: 78,
      d5_volumePersistence: 76,
      d6_releasePotential: 83,
      d7_directionalClarity: 81,
      d8_structuralCleanliness: 79,
      d9_multiTimeframeAlignment: 84,
      d10_activationQuality: 77,
      d11_triggerQuality: 75,
      d12_entryCleanliness: 78,
      d13_invalidationClarity: 80,
      d14_rewardFeasibility: 82,
      d15_runtimeTrust: 85,
      d16_stateStability: 80,
    },
  },
  {
    name: "Strong Accum / Weak Activation",
    dims: {
      d1_macroAccumulation: 82,
      d2_recentAccumulation: 78,
      d3_priceHoldIntegrity: 75,
      d4_compressionQuality: 80,
      d5_volumePersistence: 72,
      d6_releasePotential: 85,
      d7_directionalClarity: 38,
      d8_structuralCleanliness: 40,
      d9_multiTimeframeAlignment: 35,
      d10_activationQuality: 32,
      d11_triggerQuality: 28,
      d12_entryCleanliness: 30,
      d13_invalidationClarity: 25,
      d14_rewardFeasibility: 35,
      d15_runtimeTrust: 70,
      d16_stateStability: 65,
    },
  },
  {
    name: "Strong Structure / Weak Trust",
    dims: {
      d1_macroAccumulation: 58,
      d2_recentAccumulation: 55,
      d3_priceHoldIntegrity: 60,
      d4_compressionQuality: 57,
      d5_volumePersistence: 54,
      d6_releasePotential: 60,
      d7_directionalClarity: 78,
      d8_structuralCleanliness: 72,
      d9_multiTimeframeAlignment: 85,
      d10_activationQuality: 80,
      d11_triggerQuality: 65,
      d12_entryCleanliness: 68,
      d13_invalidationClarity: 70,
      d14_rewardFeasibility: 72,
      d15_runtimeTrust: 25,
      d16_stateStability: 30,
    },
  },
  {
    name: "Strong Exec / Weak Invalidation",
    dims: {
      d1_macroAccumulation: 60,
      d2_recentAccumulation: 58,
      d3_priceHoldIntegrity: 55,
      d4_compressionQuality: 57,
      d5_volumePersistence: 56,
      d6_releasePotential: 62,
      d7_directionalClarity: 63,
      d8_structuralCleanliness: 60,
      d9_multiTimeframeAlignment: 65,
      d10_activationQuality: 62,
      d11_triggerQuality: 78,
      d12_entryCleanliness: 82,
      d13_invalidationClarity: 28,
      d14_rewardFeasibility: 35,
      d15_runtimeTrust: 68,
      d16_stateStability: 65,
    },
  },
  {
    name: "High Context / Low Stability",
    dims: {
      d1_macroAccumulation: 82,
      d2_recentAccumulation: 78,
      d3_priceHoldIntegrity: 80,
      d4_compressionQuality: 75,
      d5_volumePersistence: 77,
      d6_releasePotential: 85,
      d7_directionalClarity: 58,
      d8_structuralCleanliness: 55,
      d9_multiTimeframeAlignment: 56,
      d10_activationQuality: 60,
      d11_triggerQuality: 52,
      d12_entryCleanliness: 50,
      d13_invalidationClarity: 54,
      d14_rewardFeasibility: 58,
      d15_runtimeTrust: 45,
      d16_stateStability: 22,
    },
  },
  {
    name: "Conflicting Dimensions",
    dims: {
      d1_macroAccumulation: 78,
      d2_recentAccumulation: 30,
      d3_priceHoldIntegrity: 75,
      d4_compressionQuality: 28,
      d5_volumePersistence: 72,
      d6_releasePotential: 35,
      d7_directionalClarity: 70,
      d8_structuralCleanliness: 32,
      d9_multiTimeframeAlignment: 68,
      d10_activationQuality: 30,
      d11_triggerQuality: 65,
      d12_entryCleanliness: 28,
      d13_invalidationClarity: 65,
      d14_rewardFeasibility: 30,
      d15_runtimeTrust: 62,
      d16_stateStability: 35,
    },
  },
  {
    name: "False-Positive Candidate",
    dims: {
      d1_macroAccumulation: 80,
      d2_recentAccumulation: 75,
      d3_priceHoldIntegrity: 78,
      d4_compressionQuality: 76,
      d5_volumePersistence: 72,
      d6_releasePotential: 80,
      d7_directionalClarity: 72,
      d8_structuralCleanliness: 70,
      d9_multiTimeframeAlignment: 32,
      d10_activationQuality: 68,
      d11_triggerQuality: 66,
      d12_entryCleanliness: 64,
      d13_invalidationClarity: 28,
      d14_rewardFeasibility: 62,
      d15_runtimeTrust: 38,
      d16_stateStability: 60,
    },
  },
  {
    name: "Degraded Runtime",
    dims: {
      d1_macroAccumulation: 58,
      d2_recentAccumulation: 55,
      d3_priceHoldIntegrity: 60,
      d4_compressionQuality: 52,
      d5_volumePersistence: 57,
      d6_releasePotential: 55,
      d7_directionalClarity: 56,
      d8_structuralCleanliness: 54,
      d9_multiTimeframeAlignment: 58,
      d10_activationQuality: 60,
      d11_triggerQuality: 55,
      d12_entryCleanliness: 53,
      d13_invalidationClarity: 57,
      d14_rewardFeasibility: 60,
      d15_runtimeTrust: 18,
      d16_stateStability: 25,
    },
  },
];

export const DIMENSION_LABELS: Record<
  keyof import("./d16Engine").Dimensions,
  string
> = {
  d1_macroAccumulation: "D1 — Macro Accumulation",
  d2_recentAccumulation: "D2 — Recent Accumulation",
  d3_priceHoldIntegrity: "D3 — Price Hold Integrity",
  d4_compressionQuality: "D4 — Compression Quality",
  d5_volumePersistence: "D5 — Volume Persistence",
  d6_releasePotential: "D6 — Release Potential",
  d7_directionalClarity: "D7 — Directional Clarity",
  d8_structuralCleanliness: "D8 — Structural Cleanliness",
  d9_multiTimeframeAlignment: "D9 — Multi-TF Alignment",
  d10_activationQuality: "D10 — Activation Quality",
  d11_triggerQuality: "D11 — Trigger Quality",
  d12_entryCleanliness: "D12 — Entry Cleanliness",
  d13_invalidationClarity: "D13 — Invalidation Clarity",
  d14_rewardFeasibility: "D14 — Reward Feasibility",
  d15_runtimeTrust: "D15 — Runtime Trust",
  d16_stateStability: "D16 — State Stability",
};

export const DIMENSION_SHORT_LABELS: Record<
  keyof import("./d16Engine").Dimensions,
  string
> = {
  d1_macroAccumulation: "Macro Acc.",
  d2_recentAccumulation: "Recent Acc.",
  d3_priceHoldIntegrity: "Price Hold",
  d4_compressionQuality: "Compression",
  d5_volumePersistence: "Volume Pers.",
  d6_releasePotential: "Release Pot.",
  d7_directionalClarity: "Direction",
  d8_structuralCleanliness: "Structure",
  d9_multiTimeframeAlignment: "MTF Align",
  d10_activationQuality: "Activation",
  d11_triggerQuality: "Trigger",
  d12_entryCleanliness: "Entry Clean",
  d13_invalidationClarity: "Invalidation",
  d14_rewardFeasibility: "Reward / RR",
  d15_runtimeTrust: "Runtime Trust",
  d16_stateStability: "State Stab.",
};

export const GROUP_LABELS: Record<
  keyof import("./d16Engine").GroupScores,
  string
> = {
  contextBase: "Context Base (A)",
  structuralTruth: "Structural Truth (B)",
  executionFeasibility: "Execution Feasibility (C)",
  reliability: "Reliability (D)",
};

export const GROUP_DIMS: Record<
  keyof import("./d16Engine").GroupScores,
  (keyof import("./d16Engine").Dimensions)[]
> = {
  contextBase: [
    "d1_macroAccumulation",
    "d2_recentAccumulation",
    "d3_priceHoldIntegrity",
    "d4_compressionQuality",
    "d5_volumePersistence",
    "d6_releasePotential",
  ],
  structuralTruth: [
    "d7_directionalClarity",
    "d8_structuralCleanliness",
    "d9_multiTimeframeAlignment",
    "d10_activationQuality",
  ],
  executionFeasibility: [
    "d11_triggerQuality",
    "d12_entryCleanliness",
    "d13_invalidationClarity",
    "d14_rewardFeasibility",
  ],
  reliability: ["d15_runtimeTrust", "d16_stateStability"],
};

export const DEFAULT_DIMS: Dimensions = {
  d1_macroAccumulation: 50,
  d2_recentAccumulation: 50,
  d3_priceHoldIntegrity: 50,
  d4_compressionQuality: 50,
  d5_volumePersistence: 50,
  d6_releasePotential: 50,
  d7_directionalClarity: 50,
  d8_structuralCleanliness: 50,
  d9_multiTimeframeAlignment: 50,
  d10_activationQuality: 50,
  d11_triggerQuality: 50,
  d12_entryCleanliness: 50,
  d13_invalidationClarity: 50,
  d14_rewardFeasibility: 50,
  d15_runtimeTrust: 50,
  d16_stateStability: 50,
};
